Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "eventId"
          AttributeType: "S"
        - AttributeName: "familyId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "familyId"
          KeyType: "HASH"
        - AttributeName: "eventId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "touchbase_events"