Resources:
  MembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "memberId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "memberId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "touchbase_members"